### ISSUE TITLE
在安装Optifine时遇到了问题

### ISSUE THREAD

**Issue by Sak94664** [Cat7373/HMCL#4]
log如下：
[17:02:17] [TaskList/INFO] Executing task: 获取Forge列表
[17:02:17] [pool-2-thread-1/INFO] Executing task: Get: http://files.minecraftforge.net/maven/net/minecraftforge/forge/json
[17:02:20] [AWT-EventQueue-0/INFO] Tasks have been canceled by user.
[17:02:20] [TaskList/ERROR] Task failed: 获取Forge列表
java.lang.NullPointerException

    at org.jackhuang.hellominecraft.launcher.core.install.forge.MinecraftForgeVersionList$1.executeTask(MinecraftForgeVersionList.java:77)

    at org.jackhuang.hellominecraft.util.tasks.TaskList.executeTask(TaskList.java:137)

    at org.jackhuang.hellominecraft.util.tasks.TaskList.run(TaskList.java:168)

[17:02:20] [TaskList/INFO] Executing task: 获取OptiFine列表
[17:02:20] [pool-3-thread-1/INFO] Executing task: Get: http://optifine.net/downloads
[17:02:20] [pool-2-thread-1/INFO] Task aborted: Get: http://files.minecraftforge.net/maven/net/minecraftforge/forge/json
[17:02:20] [pool-3-thread-1/WARN] Failed to download, repeat: 1
[17:02:22] [pool-3-thread-1/WARN] Failed to download, repeat: 2
[17:02:22] [pool-3-thread-1/WARN] Failed to download, repeat: 3
[17:02:22] [pool-3-thread-1/WARN] Failed to download, repeat: 4
[17:02:23] [pool-3-thread-1/WARN] Failed to download, repeat: 5
[17:02:23] [pool-3-thread-1/ERROR] Task failed: Get: http://optifine.net/downloads
org.jackhuang.hellominecraft.util.tasks.download.NetException: Failed to get http://optifine.net/downloads

    at org.jackhuang.hellominecraft.util.tasks.download.HTTPGetTask.executeTask(HTTPGetTask.java:83)

    at org.jackhuang.hellominecraft.util.tasks.TaskList.executeTask(TaskList.java:137)

    at org.jackhuang.hellominecraft.util.tasks.TaskList.access$000(TaskList.java:38)

    at org.jackhuang.hellominecraft.util.tasks.TaskList$Invoker.run(TaskList.java:86)

    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

    at java.util.concurrent.FutureTask.run(Unknown Source)

    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

    at java.lang.Thread.run(Unknown Source)

Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://optifine.net/downloads

    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

    at org.jackhuang.hellominecraft.util.tasks.download.HTTPGetTask.executeTask(HTTPGetTask.java:63)

    ... 8 more

[17:02:23] [TaskList/INFO] Task finished: 获取OptiFine列表
[17:02:23] [AWT-EventQueue-0/INFO] Tasks are finished.
[17:02:26] [TaskList/INFO] Executing task: 获取LiteLoader列表
[17:02:26] [pool-4-thread-1/INFO] Executing task: Get: http://dl.liteloader.com/versions/versions.json
[17:02:28] [pool-4-thread-1/INFO] Task finished: Get: http://dl.liteloader.com/versions/versions.json
[17:02:28] [TaskList/INFO] Task finished: 获取LiteLoader列表
[17:02:28] [AWT-EventQueue-0/INFO] Tasks are finished.
[17:03:24] [TaskList/INFO] Executing task: 获取OptiFine列表
[17:03:24] [pool-6-thread-1/INFO] Executing task: Get: http://optifine.net/downloads
[17:03:24] [pool-6-thread-1/WARN] Failed to download, repeat: 1
[17:03:25] [pool-6-thread-1/WARN] Failed to download, repeat: 2
[17:03:25] [pool-6-thread-1/WARN] Failed to download, repeat: 3
[17:03:26] [pool-6-thread-1/WARN] Failed to download, repeat: 4
[17:03:26] [pool-6-thread-1/WARN] Failed to download, repeat: 5
[17:03:26] [pool-6-thread-1/ERROR] Task failed: Get: http://optifine.net/downloads
org.jackhuang.hellominecraft.util.tasks.download.NetException: Failed to get http://optifine.net/downloads

    at org.jackhuang.hellominecraft.util.tasks.download.HTTPGetTask.executeTask(HTTPGetTask.java:83)

    at org.jackhuang.hellominecraft.util.tasks.TaskList.executeTask(TaskList.java:137)

    at org.jackhuang.hellominecraft.util.tasks.TaskList.access$000(TaskList.java:38)

    at org.jackhuang.hellominecraft.util.tasks.TaskList$Invoker.run(TaskList.java:86)

    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

    at java.util.concurrent.FutureTask.run(Unknown Source)

    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

    at java.lang.Thread.run(Unknown Source)

Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://optifine.net/downloads

    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

    at org.jackhuang.hellominecraft.util.tasks.download.HTTPGetTask.executeTask(HTTPGetTask.java:63)

    ... 8 more

[17:03:26] [TaskList/INFO] Task finished: 获取OptiFine列表
[17:03:26] [AWT-EventQueue-0/INFO] Tasks are finished.

**Comment by Cat7373** [comment]
官方版本已经重新回到huanghongxun手里了，请换回官方版本
